import React from 'react';

const AiTransparency: React.FC = () => {
  return (
    <div className="max-w-3xl mx-auto mt-12 bg-light-surface/30 dark:bg-dark-surface/30 backdrop-blur-sm rounded-lg shadow-lg p-8 border border-light-border/50 dark:border-dark-border/50">
      <h2 className="text-2xl font-bold text-center text-light-text-primary dark:text-dark-text-primary mb-6 flex items-center justify-center">
        <svg xmlns="http://www.w3.org/2000/svg" className="h-7 w-7 mr-3 text-light-brand dark:text-dark-brand" viewBox="0 0 20 20" fill="currentColor">
          <path fillRule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z" clipRule="evenodd" />
        </svg>
        How Our AI Works
      </h2>
      <div className="space-y-4 text-light-text-secondary dark:text-dark-text-secondary">
        <p>
          CareerBoard is powered by Google's Gemini models to provide you with a deeply personalized career analysis. Here's a transparent look at our process:
        </p>
        <ul className="list-disc list-inside space-y-3 pl-2">
          <li>
            <strong>Resume Analysis:</strong> Your resume text is analyzed to understand your existing skills, experiences, and projects. We compare this against the requirements of your target role and a comprehensive database of in-demand tech skills.
          </li>
          <li>
            <strong>Google Search Integration:</strong> To ensure your report is current, our AI uses Google Search to understand the latest industry trends and expectations for roles and technologies, providing you with up-to-the-minute, relevant advice.
          </li>
          <li>
            <strong>Personalized Sections:</strong> Each part of your report—from Skill Gaps to your weekly Roadmap—is generated specifically for you. The AI tailors learning resources and project ideas to bridge the exact gaps it identifies.
          </li>
           <li>
            <strong>Image Generation:</strong> The dynamic background images are generated by Gemini's image models to create a unique and inspiring visual experience tailored to your journey.
          </li>
          <li>
            <strong>Your Privacy Matters:</strong> We are committed to your privacy. Your resume data is used only for the duration of the analysis and is not stored or used for any other purpose.
          </li>
        </ul>
      </div>
    </div>
  );
};

export default AiTransparency;
